### ISSUE TITLE
Streak ends if commit locally and push next day

### ISSUE THREAD

**Issue by blackphoenix42** [DenverCoder1/github-readme-streak-stats#114]
**Describe the bug**
I had committed some changes locally but didn't push them. Today when I pushed those changes it's showing me my Streak ended and it was reset to 0.

**Comment by DenverCoder1** [comment]
Commits only get counted by GitHub when they are pushed to the main branch.

If you committed locally, it would not show up on the contribution graph until it's pushed.

Because of caching, it won't update immediately when it is pushed but could take a few hours.

It looks like it is working correctly when I look at your profile

![image](https://user-images.githubusercontent.com/20955511/127154009-1e76524e-723c-4d82-a882-7fd3c1539775.png)

**Comment by blackphoenix42** [comment]
I think it's because of caching changes are not updated yet.
Thanks for letting me know. Closing this issue.
