### ISSUE TITLE
My Streak Got Stuck At 100 Days

### ISSUE THREAD

**Issue by Aryamanz29** [DenverCoder1/github-readme-streak-stats#116]
**Describe the bug**
My Streak Got Stuck At 100 Days (Till 31st July)

**To Reproduce**
Visit my Github profile.
**Expected behaviour**
Should Show Actual Numbers

**Comment by DenverCoder1** [comment]
It appears as 102 when I checked.

The streak stats do not update instantly because of cache. It can take up to a few hours after pushing commits for them to show up.

![Screenshot_20210802-070207](https://user-images.githubusercontent.com/20955511/127802801-04c1d693-a106-490f-9476-65cc007f23b1.png)

**Comment by Aryamanz29** [comment]
@DenverCoder1  Thanks 😄 , Closing this issue Now.
