### ISSUE TITLE
Bug total contribution

### ISSUE THREAD

**Issue by adityadees** [DenverCoder1/github-readme-streak-stats#12]
this mine 
https://github-readme-streak-stats.herokuapp.com/?user=adityadees

my profile
https://github.com/adityadees

2 Total Contributions
Dec 31, 1969 - Present

0 Current Streak

1 Longest Streak
Dec 31, 1969

**Comment by DenverCoder1** [comment]
Thanks for the report!

I think this is a bug with GitHub itself.

I don't know why, but GitHub shows all years since 1969 on your profile page.

![image](https://user-images.githubusercontent.com/20955511/103625583-dc28da00-4f43-11eb-8c7e-a348d3718fe1.png)

**Comment by DenverCoder1** [comment]
It is possible that you had the date set incorrectly on some commits that were pushed.

![image](https://user-images.githubusercontent.com/20955511/103625904-3cb81700-4f44-11eb-8566-1346647b1ad7.png)

**Comment by adityadees** [comment]
> It is possible that you had the date set incorrectly on some commits that were pushed.
> 
> ![image](https://user-images.githubusercontent.com/20955511/103625904-3cb81700-4f44-11eb-8566-1346647b1ad7.png)

yes, because I set the push date manually,  and I purposely set it to 1969

**Comment by DenverCoder1** [comment]
What do you expect the result to look like instead? If the first commit was Dec 31, 1969, I'd say it is working as expected.

I could make it ignore commits in years before GitHub was launched for example. What do you suggest?

**Comment by adityadees** [comment]
> What do you expect the result to look like instead? If the first commit was Dec 31, 1969, I'd say it is working as expected.
> 
> I could make it ignore commits in years before GitHub was launched for example. What do you suggest?

Dec 31, 1969 - Present 
I think the total contribution should be counted from 1969 to 2021

**Comment by DenverCoder1** [comment]
The issue likely has to do with the way the contributions are fetched. For every year since the first year on the profile, it makes a request to that year's contribution graph. Since there are 52 years between 1969 and 2021, it needs to make 52 requests to GitHub. It is likely that some of these requests are getting blocked since they occur in close proximity.

I thought of doing the requests in reverse order to make it so recent commits will definitely show up (but not necessarily commits from 52 years ago.

Here is an example of that

![image](https://user-images.githubusercontent.com/20955511/103877011-25606180-50dd-11eb-9a32-af0e9c80cdfd.png)

Let me know if you have any ideas.

**Comment by adityadees** [comment]
try to run on local , this working fine 
![ac1](https://user-images.githubusercontent.com/37553901/103970473-e98bd180-519a-11eb-9c74-5cf44eb57daf.png)


but not working on live
![ac2](https://user-images.githubusercontent.com/37553901/103970467-e5f84a80-519a-11eb-8459-ab26f99fda10.png)

**Comment by DenverCoder1** [comment]
That is exactly what I think the issue is. It stops loading data before getting to all 52 of the contribution graphs.

**Comment by adityadees** [comment]
> That is exactly what I think the issue is. It stops loading data before getting to all 52 of the contribution graphs.

yes waiting for contributor to fix this issue xD

**Comment by DenverCoder1** [comment]
What should be done about it? Would probably have to completely change the way it works in order to request all of that data in a short amount of time from GitHub.

I could start by doing them in reverse order to make sure the current streak will be accurate, and most of the important data will be loaded.

Would it make sense to you if years between 1970 and 2008, let's say, get skipped when making the requests? That may fix the problem because it seems to me it would be very rare to put commits in those years.

**Comment by adityadees** [comment]
okay, it doesn't matter to me, but if we can fix this problem, in my opinion it's better

**Comment by DenverCoder1** [comment]
With #23 I changed the way it gets the start year to use the account creation date from the GitHub API instead of reading the HTML of the profile page.

Because of this change, commits before the account was created don't get counted making this not an issue for now.

I will continue to think of other ways to get the contributions, but I believe the way I do it is the only way since it's not a part of the public API.
