### ISSUE TITLE
Options for font family and font size

### ISSUE THREAD

**Issue by jgphilpott** [DenverCoder1/github-readme-streak-stats#204]
If it would be possible to add options for font family and/or font size I think that would be great!

Right now the text in the streak stats dost match the rest of my profile, I would like to make it match.

**Comment by DenverCoder1** [comment]
Currently the streak stats have a font stack of `Open Sans, Roboto, system-ui, sans-serif;` but since not all computers have Open Sans and Roboto installed and font imports do not work through `<img>` tags, it will usually end up being whatever the system UI font is set to.

Allowing custom fonts (eg. Google Fonts) is not so simple since the fonts would have to be fetched as CSS which adds a few extra requests to the process, unless a database is used to store pre-fetched CSS (like I have done for [readme-typing-svg](https://github.com/denvercoder1/readme-typing-svg)). I'd prefer to avoid that in Streak Stats since it is not as essential.

The other cards appearing on your page use the font stack `'Segoe UI', Ubuntu, Sans-Serif;`.

To me I don't think it makes a huge difference which font is used, although I do like the current fonts I've chosen a little better.

Current design:

![image](https://user-images.githubusercontent.com/20955511/150701583-2f0d1b0d-2b38-4108-bce0-f881803d8cb5.png)

Using `Segoe UI, Ubuntu, sans-serif`:

![image](https://user-images.githubusercontent.com/20955511/150701559-d8d72ed5-53b8-40eb-bbce-5c187ee13bdc.png)

Especially as the font stack for Streak Stats is already not very well defined, I wouldn't mind changing it to be consistent with the fonts used on other popular readme cards.

**Comment by jgphilpott** [comment]
Wow, thanks for the great reply!

I think whats happening is that the font is defaulting to my system UI font, as you mentioned in your first paragraph. I checked my profile on my phone as well and its displayed with a different font again.

This is how my profile looks on my laptop:
![Screenshot from 2022-01-24 11-35-01](https://user-images.githubusercontent.com/4128208/150749350-b235bde9-1951-47be-9cfc-35e304c2988a.png)

I think what might be best is to update the font stack to be consistent with other popular readme cards as you mentioned. It would be good to have a consistent result across devises and browsers. Personally I like `Ubuntu` and `sans-serif`.

**Comment by DenverCoder1** [comment]
I think that sounds like a good idea. It should be pretty simple to replace the fonts with `Segoe UI, Ubuntu, sans-serif`.

Would you like to make a pull request or should I?

**Comment by jgphilpott** [comment]
I made a pull request (#208), hope its okay.
