### ISSUE TITLE
Streak ring overlapping the icon

### ISSUE THREAD

**Issue by Deepakmukka1** [DenverCoder1/github-readme-streak-stats#211]
**Describe the bug**
2 of the themes (cobalt, onedark_duo) is not displaying as expected, the ring around the current streak over laps the fire icon

**To Reproduce**
1. Go to https://github-readme-streak-stats.herokuapp.com/demo/
2. Click on Theme
3. Scroll down to cobalt or onedark_duo

**Expected behavior**
The icon should come above the ring creating an effect like this

![image](https://user-images.githubusercontent.com/56472120/151743339-ec7f036c-0c44-47b6-90df-563caf68e922.png)

**Screenshots**
Current behavior

![image](https://user-images.githubusercontent.com/56472120/151743367-d95f3b07-d64a-4c24-bfdd-3a4e94f7db98.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: [chrome, brave]
 - Version: 97.0.4692.99

**Comment by DenverCoder1** [comment]
It seems to be an issue with all transparent themes (cobalt and all themes ending with _duo)

Using the background color behind the fire to mask out part of the ring isn't going to work if the background is transparent.

A different way of masking out the ring is likely required. The fix for this will probably also fix #151.

**Comment by DenverCoder1** [comment]
The issue should be fixed now. I expected it to be more difficult than it was.

Let me know if there are still any issues.
