### ISSUE TITLE
toLocaleString() on Total Contributions number (1234 => 1,234)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [DenverCoder1/github-readme-streak-stats#235]
The total contributions should have a comma after the thousands place. In JavaScript, this is handled with `value.toLocaleString()`, which the browser then checks the user's locale and formats the number. This is because in some cultures, like German, they would use `1.234` instead of `1,234`. So perhaps infer this from the `locale` setting, using `en` as default. Assuming PHP has some similar number locale formatting library.

![example](https://github-readme-streak-stats.herokuapp.com/?user=TheJaredwilcurt&theme=dark&ring=5325ED&fire=5325ED&currStreakLabel=5325ED&dates=E9F1F9&sideLabels=C9D1D9&sideNums=C9D1D9&currStreakNum=C9D1D9)

**Comment by DenverCoder1** [comment]
That sounds great. I don't know why I never really felt it was needed, but it's definitely something that could be added.

In PHP, there is a [NumberFormatter](https://www.php.net/manual/en/numberformatter.format.php) class.

So we could do something like this for example:

```py
$numFormatter = new NumberFormatter($locale, NumberFormatter::DECIMAL);
...
$totalContributions = $numFormatter->format($stats["totalContributions"]);
```

Possibly the locale parameter could be changed to allow locales that there are no translations for so that the numbers can still be formatted.

Would you want to contribute a PR, or do you prefer I do it?

**Comment by TheJaredWilcurt** [comment]
You should handle it, I only know JS.
