### ISSUE TITLE
IMPORTANT: Heroku is no longer offering free plans

### ISSUE THREAD

**Issue by MagicLike** [DenverCoder1/github-readme-streak-stats#318]
**Is your feature request related to a problem? Please describe.**
Heroku is no longer offering free plans.

**Describe the solution you'd like**
Another way of hosting Github Readme Streak Stats, like Vercel & Docker.

**Comment by DenverCoder1** [comment]
For the documentation, feel free to contribute alternate ways to self-host if you know of any simple, reliable options.

As far as the main deployment, I'll probably end up switching to a Heroku paid plan if I have to in order to keep the domain.

I've been in touch with Heroku's Open Source Program office about their plans for Open Source support which may allow it to be hosted discounted or for free. The selection criteria is not yet finalized so it may take a few more weeks before I can know for sure.

For now, things can stay as is since the removal of free plans only goes into effect on November 28.

More info about the Heroku changes including info about possible Student, Nonprofit, and Open Source support:
https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

**Comment by nishith-p-shetty** [comment]
i made a docker support. i will be opening a pull request shortly.

**Comment by DenverCoder1** [comment]
I'll be keeping it on Heroku for the time being. Heroku will be sponsoring free credits for the project through the Open Source Program at least until February (and probably after as well once things are finalized by them).

Anyone who is interested in more info on Open Source credits should contact [ospo-heroku-credits@salesforce.com](mailto:ospo@salesforce.com).
