### ISSUE TITLE
Local translate to tamil

### ISSUE THREAD

**Issue by pravee42** [DenverCoder1/github-readme-streak-stats#333]
![image](https://user-images.githubusercontent.com/65100038/195879744-ce7faec1-3ff9-425a-9330-f36a46363921.png)

1. I would like to contribute to translating the language to Tamil for users from Tamil Nadu

**Comment by DenverCoder1** [comment]
It would be great to have you contribute. Feel free to take a look at #236 for additional details on contributing translations.

**Comment by pravee42** [comment]
I have made the PR as per the issue you have mentioned but there is error in checks

**Comment by DenverCoder1** [comment]
> I have made the PR as per the issue you have mentioned but there is error in checks

The error in checks is because of the extra spaces at the beginning of the line, and also that it was placed out of alphabetical order, at the end, rather than between ru and tr. 

If you'd like to try fixing that, you may, although it's something that I can resolve quickly before merging if you prefer.

**Comment by pravee42** [comment]
![image](https://user-images.githubusercontent.com/65100038/196021206-eaee1a82-d99e-44b0-a4f1-f1a25978c1aa.png)

The responsiveness somewhat looks messy.

**Comment by DenverCoder1** [comment]
It seems like the font it is using for you is different than how it displays for me

**Comment by pravee42** [comment]
> It seems like the font it is using for you is different than how it displays for me

yes

**Comment by DenverCoder1** [comment]
I suppose it could be fixed by adding a newline (`"\n"`) in the total contributions and removing the middle word from longest streak.

Something like this maybe.

```php
    "ta" => [
        "Total Contributions" => "மொத்த\nபங்களிப்புகள்",
        "Current Streak" => "மிக சமீபத்திய பங்களிப்புகள்",
        "Longest Streak" => "நீண்ட பங்களிப்புகள்",
        "Present" => "இன்றுவரை",
    ],
```

![image](https://user-images.githubusercontent.com/20955511/196021337-a4d649cf-b95b-4ed2-95ea-81649ea948d0.png)

Either works for me, but if you'd like, we can change it to make it look better on your computer.

If you'd like to open another pull request, feel free.

**Comment by pravee42** [comment]
> 

If there is any option to change the font here

**Comment by pravee42** [comment]
![image](https://user-images.githubusercontent.com/65100038/196021463-e5c067d1-5104-459f-bdeb-c7645f8b8a25.png)
 
I have edit the font size option here

**Comment by DenverCoder1** [comment]
Changing the font wouldn't be so simple, currently it uses the same font stack as GitHub. Maybe installing Segoe UI or Ubuntu could help, but I'm not sure.

Making the font size configurable might help. I wouldn't want to change it for every language since it already looks fine for most. Maybe an option for each language would be ok, similar to how we have `"rtl" => true` for right to left, there could be something like `"size" => "14px"` or similar. I'd rather the text just fit with the same font and size for everything if possible though.

**Comment by pravee42** [comment]
> 

i have opened the pull request as per your idea please check it out
