### ISSUE TITLE
My streak stats can't update

### ISSUE THREAD

**Issue by Kumilachew-g** [DenverCoder1/github-readme-streak-stats#374]
**Description**

A brief description of the question or issue:

**Comment by DenverCoder1** [comment]
Can you describe what the issue is?

**Comment by Jkalio52** [comment]
I'm noticing the same issue as well (streak stats not updating, the "Current Streak" is way off, like in the hundreds. Mine shows 7 instead of 240+), and getting emails from GitHub regarding failed github-readme-stats (screenshot below) 

The email subject line contains the following: ".../github-readme-stats] Run failed: Update top issues dashboard - master (9eb0c3c)" 

The email body: "Update top issues dashboard: All jobs have failed"
![image](https://user-images.githubusercontent.com/30821820/209069836-b968601c-2cf7-45a9-ace2-037c51c0b8a7.png)

I'm not sure if this will help but, I'll provide the full link if needed. Thank you!

**Comment by DenverCoder1** [comment]
> Mine shows 7 instead of 240+

GitHub shows that you have no contributions on December 13. If it shows differently for you, it's because you're in a different timezone. The timezone can't be changed in the API call, so the only option you have to fix your steak is to change the dates of past commits or create commits while setting the date to the date that is missing. (Check the [FAQ](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph)).

> getting emails from GitHub regarding failed github-readme-stats

This is not relevant to the issue. Github-readme-streak-stats is not a GitHub action, it is just a dynamic image, so this action that is failing must be a different project entirely.

**Comment by DenverCoder1** [comment]
The data is fetched from the GitHub API. GitHub caches images for a few hours at a time, so it won't update immediately after a contribution is made. It can take a few hours to update.
