### ISSUE TITLE
Feature request: Exclude weekends?

### ISSUE THREAD

**Issue by jamesowers-roo** [DenverCoder1/github-readme-streak-stats#408]
**Is your feature request related to a problem? Please describe.**
My max streak is 5 - I either don't code on the weekend, or use another account 😭 . I would like to be incentivised to push something every weekday.

**Describe the solution you'd like**
It would be awesome to have an 'exclude weekends' option in the config demo page https://streak-stats.demolab.com/demo

**Describe alternatives you've considered**
I could use the weekly version of the streak, but this doesn't incentivise me to code every day within the work week, so doesn't satisfy the requirement on this feature request.

**Additional context**
N/A.

**Comment by DenverCoder1** [comment]
Great idea! I actually already had this in mind, but just hadn't gotten around to implementing it yet.

It may be worth considering that not all countries consider weekends to be the same days (sometimes Sunday is considered the weekend, sometimes not). Friday may also be a day off from work.

I think to implement this in the most flexible way, rather than making separate mode for excluding weekends or a toggle, it could be a list of days of the week to exclude.

* Exclude weekdays with abbreviations (`exclude_weekdays=Sun,Sat`)
  * Easily readable and modifiable
  * May want to possibly consider variations in case, spelling, etc?
* Exclude weekdays with numbers 0-6 (`exclude_weekdays=0,6`)
  * Takes up less space
  * Can be confusing (not all countries start weeks with the same day, is it 0 or 1-indexed, etc)

Another possible thing to consider is how or whether it would be differentiated from the regular daily streak.

Possibly it could say "Excluding weekends" in the corner or something similar, or perhaps change "Current Streak / Longest Streak" to "Current Weekday Streak / Longest Weekday Streak" similar to Weekly mode.

Feel free to share your thoughts on this.

**Comment by jamesowers-roo** [comment]
I think these are all brill solutions. I think I favour your first point - and for brevity you could go with:
* exclude_days=Mon,Sat,Sun
* optional add to streak graphic further abbreviated version (you can control this) `excl. Mo, Sa, & Su`

Have never coded in js / php before, but if you point me to the files I should look at, and a method of testing my solution, I'd be delighted to contribute a PR.

**Comment by DenverCoder1** [comment]
Relevant files:

* [stats.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/fc1ce8ebc2260306f83a84a4ccb4b96f1365d3ab/src/stats.php) - a parameter could possibly be added to [`getContributionStats`](https://github.com/DenverCoder1/github-readme-streak-stats/blob/fc1ce8ebc2260306f83a84a4ccb4b96f1365d3ab/src/stats.php#L276) to specify which days of the week to exclude when calculating the results.
* [index.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/fc1ce8ebc2260306f83a84a4ccb4b96f1365d3ab/src/index.php) - The days to exclude should be passed to the method above [where it is called](https://github.com/DenverCoder1/github-readme-streak-stats/blob/fc1ce8ebc2260306f83a84a4ccb4b96f1365d3ab/src/index.php).
* [card.php](https://github.com/DenverCoder1/github-readme-streak-stats/blob/fc1ce8ebc2260306f83a84a4ccb4b96f1365d3ab/src/card.php) - something in the SVG in [`generateCard`](https://github.com/DenverCoder1/github-readme-streak-stats/blob/fc1ce8ebc2260306f83a84a4ccb4b96f1365d3ab/src/card.php#L294) should probably be added to distinguish the card in appearance from a regular daily streak based on whether days are excluded (eg. "excl. Mo, Sa, & Su", etc)
* Updates to the [demo site](https://github.com/DenverCoder1/github-readme-streak-stats/blob/fc1ce8ebc2260306f83a84a4ccb4b96f1365d3ab/src/demo/index.php#L134-L138) should probably be made to accommodate the new parameter.
* Some unit tests should also be added as needed

There's some info on getting things running in [contributing.md](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/CONTRIBUTING.md).

I could probably get this done this week or next, but feel free to let me know if you're still interesting in helping out.
