### ISSUE TITLE
How can we make proper 'hindi' language typespace in 'HINDI' streak card?

### ISSUE THREAD

**Issue by SAD0XER** [DenverCoder1/github-readme-streak-stats#411]
If you see _marathi_ streak card there the numbers are in a proper _marathi_ language. Like this ⬇️👇⬇️👇

![Marathi streak card](https://user-images.githubusercontent.com/79737447/211129514-b1388cbd-2269-4633-89c2-6bb8baabf84e.png)

But if you see _hindi_ then the numbers are not in _hindi_ they are in _english_. Like this ⬇️👇⬇️👇

![Hindi streak card](https://user-images.githubusercontent.com/79737447/211129636-c9a6e33b-4afd-4dad-bd4c-ec37f62e6257.png)

So can we convert those numbers into _hindi_ language? Like this ⬇️👇⬇️👇
![Hindi number screenshot](https://user-images.githubusercontent.com/79737447/211129860-1cc7f62f-ba44-4e0c-b2c3-c8f85c59148c.png)

You can see this website for reference: https://fonthindi.blogspot.com/2014/01/type-complex-hindi-numbers-symbols.html

**Comment by DenverCoder1** [comment]
Good question.

The project uses PHP's [NumberFormatter](https://www.php.net/manual/en/class.numberformatter.php) which I believe uses standards defined by ICU. As far as I know, there isn't currently a way to change the number format without specifying a different language.

**Comment by SAD0XER** [comment]
Does it mean PHP's Number Formatter doesn't know about the HINDI language?
😂 LOL just kidding!


Already I have set ```hi``` to the locale attribute.

I saw [locales.md](https://gist.github.com/DenverCoder1/f61147ba26bfcf7c3bf605af7d3382d5), there are two type of **hindi**'s, one is ```hi``` and second is ```hi_IN```.

So, I think we should change ```hi``` to ```hi_IN``` in ```translations.php``` file, so it will change the streak card completely.



###### PS: I haven't deployed this project on my machine. so I am unable to see changes. so can I open Pull Request for this?

**Comment by DenverCoder1** [comment]
`hi_IN` works the exact same way as `hi` since India is the default country for Hindi. So it's better to just leave it as just `hi`.

I think the only way to do this is by making a way to use a two different different locales for labels and for numbers.

**Comment by SAD0XER** [comment]
Sorry, but I have reverse question on it, If ```hi``` and ```hi_IN``` works the exact same way then why did they make ```hi_IN``` or ```hi``` two different locales?
There should be something difference between them.!?
____
Are you saying for ```hi``` locale write different card translation and for ```hi_IN``` locale write different?
Right?

**Comment by DenverCoder1** [comment]
`hi_IN` is just a more specific way of saying `hi`. They always have a version with the country specified and one without the country specified. The one without the country specified defaults to the primary country for the language and it allows writing it in a shorter way. It only really makes a difference when there are multiple dialects of a language eg. `pt_BR` (Portuguese Brazil) and `pt_PT` (Portuguese Portugal) can have some slight differences so you can treat them separately. Since Hindi doesn't have differences between countries, `hi` and `hi_IN` are effectively the same.

It's possible to write separate translations for `hi_IN`, but it's not necessary since currently it will use the translations for `hi` no matter which country is specified.

With number and date formats it uses the locale exactly as specified in the parameter, so you can see that `hi_IN` does the same as `hi` , eg. https://streak-stats.demolab.com/?user=DenverCoder1&locale=hi_IN

**Comment by SAD0XER** [comment]
Wow, wonderfully explained. It clear my doubt.

From Your this reply,
> Good question.
> 
> The project uses PHP's [NumberFormatter](https://www.php.net/manual/en/class.numberformatter.php) which I believe uses standards defined by ICU. As far as I know, there isn't currently a way to change the number format without specifying a different language.

It means php Number Formatter doesn't have proper real _hindi_ numbers. Right?

If NO then why ```mr``` locale has it's perfect standard number.

**Comment by DenverCoder1** [comment]
As far as I can tell it seems like the people who decided the international number formatting standards thought that Arabic numerals (0-9) were more commonly used in Hindi than Devanagari numerals, so that's what it outputs when formatting for Hindi.

**Comment by SAD0XER** [comment]
If your saying is real then they peoples are Ultra-Pro-Max-Great! who decided to do this.

Anyways, then what if we change php Number Formatter? ;)
It sounds silly but is it possible to do this?
At least we can report to php maintenaners.
