### ISSUE TITLE
Streak Reset for no reason 

### ISSUE THREAD

**Issue by Murali03M** [DenverCoder1/github-readme-streak-stats#430]
Describe the bug
I'm contributing and coding every day, but today it reset all of a sudden for no reason.

Expected behavior
It was supposed to continue

Screenshots
<img width="682" alt="image" src="https://user-images.githubusercontent.com/73110751/215039003-aa327805-5c7b-45c8-9aef-317270a21b88.png">

.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac os Ventura 13.1
- Browser  chrome
- Version latest

My streak card - 
<img width="682" alt="image" src="https://user-images.githubusercontent.com/73110751/215039315-3560c081-2515-4882-82a6-b6c5318dd0ae.png">

**Comment by DenverCoder1** [comment]
The Github API has a specific timezone so there isn't anything that can be done to fix it. This is what it shows when I view it.

![Screenshot_20230127-023837](https://user-images.githubusercontent.com/20955511/215055074-c5fce7d0-be22-41e9-8fc6-a01f3cf0e3d2.png)

If the contributions are in private repos, make sure to enable the setting for counting contributions in private repos. If the issue is with timezones, the only solution is to modify or add commits to fill in the gap (see https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph)
