### ISSUE TITLE
Let commits to PR increase contribution streak

### ISSUE THREAD

**Issue by Ishaan2053** [DenverCoder1/github-readme-streak-stats#431]
**Is your feature request related to a problem?**

When commits are made to existing Pull Requests, the card **doesn't count it as a contribution** while GitHub contribution squares turn green under similar circumstances, counting it as a contribution.

**Describe the solution you'd like**
To make the stats card count these commits as contribution to make it in line with how GitHub counts contributions.

**Describe alternatives you've considered**
none 🙂

**Additional context**

---

The card doesn't show the commit to existing PRs as a contribution (New streak starts from 23, breaking the previous one despite a contribution on 22 January)
![image](https://user-images.githubusercontent.com/113186458/215154976-10f16431-7783-4a50-8600-af193c79a57e.png)

---

Official GitHub squares count it as a valid contribution though (Day of contribution highlighted is 22 January 2023)
![image](https://user-images.githubusercontent.com/113186458/215154860-e21c1c05-03d4-4411-830d-d90bb0880986.png)

**Comment by DenverCoder1** [comment]
I can't change how it's calculated since I am getting the data directly from GitHub.

GitHub does not count commits in pull requests until they are merged into a main or gh-pages branch.

See here for the details of how contributions are counted: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

If the contributions are in private repos, make sure to enable the setting for counting contributions in private repos. If the issue is with timezones, the only solution is to modify or add commits to fill in the gap (see https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md#why-doesnt-my-streak-stats-match-my-contribution-graph)

**Comment by Ishaan2053** [comment]
Well, I went through it and I see there's nothing we can do about it. I'm closing this issue as resolved
