### ISSUE TITLE
Not sure if bug or misunderstanding of how to use.

### ISSUE THREAD

**Issue by Scrumpyy** [DenverCoder1/github-readme-streak-stats#448]
**Description**
Hey all, trying to add my streak to my profile at the moment and i'm using the below;
`<img src="https://streak-stats.demolab.com/?user=Scrumpyy&theme=holi-theme&hide_border=true&ring=EB5454&background=EB545400">`

When I directly go to `https://streak-stats.demolab.com/?user=Scrumpyy&theme=holi-theme&hide_border=true&ring=EB5454&background=EB545400` the expected image loads, however when rendering it on my profile it fails to, upon further inspection it appears that the `camo.githubusercontent.com` is returning `"Error Fetching Resource"` -- not sure if this is a bug with my implementation or with the website itself.

**Comment by DenverCoder1** [comment]
GitHub has a time limit on how long it will give for the image to load. I think the issue is probably because your contribution years go all the way back to 1970 (streak stats can only fetch 1 year at a time, so it's 1 request per year of contributions).

Changing the dates on those backdated commits would probably resolve the issue, but maybe something like streak stats adding the ability to be able to provide a minimum year to check or something could help?

**Comment by Scrumpyy** [comment]
Haha- yeah that makes sense.

> but maybe something like streak stats adding the ability to be able to provide a minimum year to check or something could help?
This would be a nice addition.

**Comment by DenverCoder1** [comment]
Feel free to let me know what you think of the proposed solution.

It will exclude years before account creation which limits the amount of requests that need to be made.

In this case, it would count contributions from 2019-2023 (4 requests) instead of 1970-2023 (52 requests)

![image](https://user-images.githubusercontent.com/20955511/217326820-214ead22-6cb1-4092-95c5-47d18ec72220.png)

**Comment by Scrumpyy** [comment]
That works for me! The 1970 exception isn't really needed but if it's not too much of an issue to implement then it would be a nice addition.

**Comment by DenverCoder1** [comment]
Thanks for reporting the issue.

You may need to give it some time for GitHub's cache to reset (or change the URL slightly to force it to refresh), but with the latest version, it should only fetch 1970 and 2019-2023.

<img src="https://streak-stats.demolab.com/?user=Scrumpyy&theme=holi-theme&hide_border=true&ring=EB5454&background=EB545400">
