### ISSUE TITLE
Showig incorrect number of streaks

### ISSUE THREAD

**Issue by el3ktraz** [DenverCoder1/github-readme-streak-stats#544]
![Screenshot_6](https://github.com/DenverCoder1/github-readme-streak-stats/assets/86217941/e9ab6655-4ab5-4dbf-9d2c-643b60cc4b03)
![Screenshot_26](https://github.com/DenverCoder1/github-readme-streak-stats/assets/86217941/0d7eecb2-b855-4023-9e0f-f6b361d18b7e)

i have continues streak and my streak status is showing till jul 21 only , i didnt break any streaks

**Comment by rica213** [comment]
I am having the same issue.

👉🏽 https://github.com/rica213

The issue started in the 20th of July

My contributions: never missed a day 👇🏽 

![Screenshot from 2023-07-25 01-50-20](https://github.com/DenverCoder1/github-readme-streak-stats/assets/10439283/41f5a893-a972-4474-b3c9-2941071ecb28)

Yet my streak is restarting  👇🏽 

![Screenshot from 2023-07-25 01-50-44](https://github.com/DenverCoder1/github-readme-streak-stats/assets/10439283/1c9e1a28-d2bd-424e-9d69-ed0e4128a707)

**Comment by DenverCoder1** [comment]
![Screenshot_20230724-232231](https://github.com/DenverCoder1/github-readme-streak-stats/assets/20955511/e2a1ad12-0576-4827-a7b0-0aa8fa196bca)

The results displayed represent whatever the GitHub API returns, it can give different results for different people possibly due to timezones.

It's possible to manually add commits to fill in the dates that are missing if you want, there's more info in the [FAQ](https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs/faq.md).
