### ISSUE TITLE
Inaccurate streak stats not fixed

### ISSUE THREAD

**Issue by asare4u** [DenverCoder1/github-readme-streak-stats#696]
A couple of issues has been raised about the streak stast being inaccurate but I haven't seen any comment nor fix of the problem.
Can you guys kindly let us know the reason?
We getting feedback in a form of comment on couple issues or fix of bug will be a bit satisfiable than we not getting any feedback from you guys.
Thank you.

**Comment by DenverCoder1** [comment]
The stats are fetched directly from the GitHub API which has not always been consistent with results. There's nothing that can be changed on our end since we display whatever it tells us. 

If you'd like to affect what is shown, you can fill in missing dates by "backdating" commits to a specific time in the middle of the day as is shown in the FAQ: https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs%2Ffaq.md#why-doesnt-my-streak-stats-match-my-contribution-graph
