### ISSUE TITLE
The streak isnt updating

### ISSUE THREAD

**Issue by Mridul47** [DenverCoder1/github-readme-streak-stats#706]
<h1> The streak isnt updating even tho i have pushed my code in a public repo of mine.</h1>

**Comment by DenverCoder1** [comment]
What number do you expect it to say and what does it say instead? 

Note: the stats are directly from the GitHub's api so there's nothing that can be done to change the calculation. Because of GitHub caching images, it can take a few hours to update.

**Comment by pranavbalu1** [comment]
![image](https://github.com/user-attachments/assets/4925f024-809a-4ad0-aeb9-aabd2f697f7c)
Here, I'm having the same problem
![image](https://github.com/user-attachments/assets/c05924e0-6a7d-432d-adb9-b50aedbd7854)

**Comment by dxps** [comment]
Same here!
| streak stats | contributions stats |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/dba6eecd-683b-4f04-b05a-2c01dfec1b95) |![image](https://github.com/user-attachments/assets/88a14834-a4f2-451c-825d-64efc2469b6d) |

**Comment by DenverCoder1** [comment]
Due to timezone differences between the charts and the GitHub API, the streak stats and the contribution graph won't necessarily match.

If there are missing days and it matters that they show up, one option you have is to manually add commits with the time set to the middle of the day on the day that is missing. More info in the FAQ - https://github.com/DenverCoder1/github-readme-streak-stats/blob/main/docs%2Ffaq.md#why-doesnt-my-streak-stats-match-my-contribution-graph

**Comment by dxps** [comment]
@DenverCoder1 You're absolutely right! Read the FAQ entry, done and solved the case.
