### ISSUE TITLE
Add Cookie Banner to the Demo Website

### ISSUE THREAD

**Issue by schmelto** [DenverCoder1/github-readme-streak-stats#92]
Due the dark mode is set via Cookie parameter I think it would be recommended to add a cookie banner to the website

**Comment by DenverCoder1** [comment]
Hi, thanks for opening this issue. I have looked into it and, as I expected, the site should be exempt from all cookie warnings since it does not store any information that can be used to identify a user. It simply uses a dark mode preference that the user specifically requests in order to restore it in the next session. Cookies that are strictly necessary for a service the user requests are also exempt.

https://iapp.org/news/a/looking-to-comply-with-gdpr-heres-a-primer-on-anonymization-and-pseudonymization/
