### ISSUE TITLE
current streak and total contribution count doesn't update automatically.

### ISSUE THREAD

**Issue by predator2v0** [DenverCoder1/github-readme-streak-stats#95]
**Describe the bug**
- the changes in my repo and contributions doesn't automatically reflect on the streak counter. however, opening the link in a separate tab manually shows the correct data.
**To Reproduce**

**Expected behavior**
- it is expected to get updated when some changes are made and committed to the repositories of the corresponding user.

**Desktop (please complete the following information):**
 - OS: windows 
 - Browser: chrome
 - Version: 10

**Smartphone (please complete the following information):**
 - Device: moto g4 plus, asus zenfone max m2
 - OS: android 7.0, android 9
 - Browser: chrome

**Comment by DenverCoder1** [comment]
Due to GitHub's caching and limitations on how frequently GitHub will allow requesting data, it wouldn't be possible to make it update automatically, but we may be able to make it expire more frequently. Currently the data expires at the end of each day, but I could look into making it refresh every few hours instead.

**Comment by predator2v0** [comment]
Thank you @DenverCoder1 for the brief and nice explanation. it could be more interactive and eye-catching if it gets updated more frequently, but there is absolutely no problem if it gets updated at the end of each day.
